import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Suspense } from "react";
import React from "react";
import TopBarAuthButtons from "@/components/TopBarAuthButtons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function TopBar() {
  // Use a client component for session logic
  return (
    <nav className="w-full bg-[#101c2c] border-b border-[#22335b] px-4 py-3 flex items-center justify-between">
      <Link href="/" className="text-xl font-bold text-[#5fa0cf] tracking-tight">MakEMinds</Link>
      <Suspense fallback={null}>
        <TopBarAuthButtons />
      </Suspense>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopBar />
        {children}
      </body>
    </html>
  );
}
